spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.93.132:8848
#在bootstrap.yml里面指定了要关联的配置文件（nacos控制台已经添加了的）就不用在此指定端口号
#server:
#  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com:
      example:
        provider:
          data:
            mapper: info