#以下有关spring的配置全部在bootstrap.yml已定义，此处不用定义
#spring:
#  application:
#    name: nacos-provider
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.93.132:8848
#在bootstrap.yml里面指定了要关联的配置文件（nacos控制台已经添加了的）就不用在此指定端口号
#server:
#  port: 8083
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#配置redis
spring:
  redis:
    host: 192.168.93.133
    port: 6379
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        #连接池中的最大空闲连接 默认 8
        max-idle: 8
        #连接池中的最小空闲连接 默认 0
        min-idle: 0
  main:
    allow-bean-definition-overriding: true